### ISSUE TITLE
Use boutiques to infer inputs/outputs in FSL command lines

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#11]
**Is your feature request related to a problem? Please describe.**
When reading the logs in FSL (e.g. [this one](https://github.com/incf-nidash/nidmresults-examples/blob/master/fsl_default/logs/feat2_pre#L28)), we have no way to automatically find out what option/parameter is an input and what open/parameter is an output.

**Describe the solution you'd like**
As discuseed on January 9, we would like to rely on the Boutiques standard to find which files are inputs and outputs of a given activity (command from the logs) in FSL.

**Describe alternatives you've considered**
Alternative would be to use a yml file as was done for SPM (to specify that c1/c2 are outputs of segment).

**Additional context**
Boutiques standard : https://boutiques.github.io/
A Boutiques file example : https://zenodo.org/record/7435009#.Y7ve--LMLz8 (for FSL siena)

**Comment by thomasbtnfr** [comment]
I have just studied boutiques, here are several points that I think are interesting:

- We have **only 3 functions described in zenodo** for the nidm examples. In total, we have **32 unique function names** in the nidm examples and this number rises to **68 if we take the command path** (which sometimes takes into account the version of fsl for example). I have saved the names, I can share them.
- For each command/function, **the inputs in boutiques (e.g. file name) are not separated from the attributes**. The **outputs are well separated from the rest**, which is useful for creating entities. For the input entities, this is not very practical. We could maybe add an "heuristic" to indicate if the parameter contains the word "file" in its description because each parameter has a description and it seems that it is repetitive...
- Some commands like this one `/usr/local/packages/fsl-5.0.8/bin/fslstats thresh_zstat1 -l 0.0001 -R 2>/dev/null` **do not specify all parameter names**. So is `thresh_zstat1` an input? In this case, I think, boutiques is not useful. From my point of view, this can be verified without boutiques by looking at the entities already created so far. If we find it, it must be an entity I think, otherwise good question (an output entity ?).
- For some parameters like `-searchrx -90 90 -searchry ...`, boutiques is interesting because it indicates the number of values for a parameter. Thus, we know that `-90` and `90` are two values of the attribute `searchrx` and that `-90` is not an attribute name. However, with an improved regex we could also manage (currently -90 is considered as an attribute name).

Overall, I have mixed feelings about boutiques. The module could be interesting if it had more functions. What is your opinion @cmaumet ?

**Comment by cmaumet** [comment]
@thomasbtnfr! I agree with your comments. We do need a way to infer inputs/outputs for each Activity. Do you think that it would be easier to use something similar to what we have done for SPM, i.e. through a config file like: https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/master/bids_prov/spm_config.yml#L2-L6? Maybe we can do this as a first step and chat with Boutiques folks on how to contribute those. Would be great if you can share the list of 32 (68) unique functions with me, I think that's tractable :)

**Comment by thomasbtnfr** [comment]
In the first instance, I think that yes, this is a more appropriate solution.

Here is the list of the 32 function names I obtained:
```
printf
imrm
rm
ln
mcflirt
flirt
fsl_sub
overlay
feat_model
fsl_tsplot
immv
mv
fslmerge
mainfeatreg
film_gls
susan
bet2
fslFixText
mkdir
fslmaths
paste
fslroi
convert_xfm
pngappend
fslstats
cp
echo
contrast_mgr
slicer
featregapply
epi_reg
mp_diffpow.sh
```

**Comment by cmaumet** [comment]
Thank you! An alternative/complementary solution, would be to check if we can leverage `yesworkflows`. The corresponding paper is: https://arxiv.org/abs/1502.02403.

**Comment by thomasbtnfr** [comment]
Finally, after fixing a reading bug in this [PR](https://github.com/bids-standard/BEP028_BIDSprov/pull/90) (which has already been merged), we have **38 function names in nidm_examples**. If we also take the whole command and not just the function name, we have **85 commands** instead of the original 68.

Here is the list (38) updated:
```
overlay
epi_reg
paste
fsl_tsplot
featregapply
fslmaths
tsplot
cluster
mp_diffpow.sh
fslFixText
mcflirt
cluster2html
fslmerge
slicer
susan
film_gls
mkdir
imrm
ln
ptoz
echo
mv
flirt
immv
fslroi
fslstats
printf
fsl_sub
contrast_mgr
convert_xfm
bet2
feat_model
pngappend
smoothest
mainfeatreg
rmdir
rm
cp
```

I am currently creating a description file of these functions to more easily retrieve the inputs (used) and outputs (generatedBy).

**Comment by thomasbtnfr** [comment]
`boutiques` is not currently used.  
A **description file** was preferred for FSL and AFNI which is more flexible and suitable for our case. The drawback of our solution is that it is less convenient to contribute to it than from boutiques because our solution is specific to the project repository. To contribute, you have to commit to the project.
