### ISSUE TITLE
Update of AssociatedWith and GeneratedBy keys in the specification

### ISSUE THREAD

**Issue by thomasbtnfr** [Inria-Empenn/BEP028_BIDSprov#12]
I propose to update the **AssociatedWith** and **GeneratedBy** keys of the Bids-prov standard to **wasAssociatedWith** and **wasGeneratedBy** respectively for the generation of graphs from jsonld.

### Problem Statement
If we keep for example **AssociatedWith** then when generating the graph, **these arrows will not appear**. It's the same case for **GeneratedBy**.

### Rationale
AssociatedWith should become wasAssociatedWith
GeneratedBy should become wasGeneratedBy

### Minimal example
Example with wasAssociatedWith in key:
![image](https://user-images.githubusercontent.com/115700860/212041064-67ff5846-4c4d-4525-9555-4c191f16aee3.png)

Example with AssociatedWith in key:
![image](https://user-images.githubusercontent.com/115700860/212041179-f75c4627-2b55-43bb-84b3-407cfb53fc5d.png)

**Comment by cmaumet** [comment]
Thanks @thomasbtnfr! I think we should be able to keep `AssociatedWith` and `GeneratedBy`in the BIDS-Prov standard but update the context file so that the keyword `AssociatedWith` is mapped to `prov:wasAssociatedWith` 

For example in https://github.com/bids-standard/BEP028_BIDSprov/blob/be57ea2568f333a54f72a153e38681e7bd8472e2/context.json#L32-L35 instead of 

```
        "wasAssociatedWith" : {
          "@id": "prov:wasAssociatedWith",
          "@type": "@id"
        },
```

we would have

```
        "AssociatedWith" : {
          "@id": "prov:wasAssociatedWith",
          "@type": "@id"
        },
```

(and similarly for `GeneratedBy`)

**Comment by thomasbtnfr** [comment]
Thanks for the example, I agree !
